# Generated by Django 3.2.3 on 2022-02-03 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('picture', models.ImageField(upload_to='products/%Y/%m/%d')),
                ('picture2', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('picture3', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('picture4', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('price', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('is_amazing', models.BooleanField(default=False)),
                ('amazing_till', models.CharField(blank=True, max_length=10, null=True)),
                ('off_price', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='WebInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_1', models.ImageField(upload_to='banners/%Y/%m/%d')),
                ('banner_2', models.ImageField(blank=True, null=True, upload_to='banners/%Y/%m/%d')),
                ('banner_3', models.ImageField(blank=True, null=True, upload_to='banners/%Y/%m/%d')),
                ('banner_4', models.ImageField(blank=True, null=True, upload_to='banners/%Y/%m/%d')),
                ('small_banner_1', models.ImageField(blank=True, null=True, upload_to='banners/%Y/%m/%d')),
                ('small_banner_2', models.ImageField(blank=True, null=True, upload_to='banners/%Y/%m/%d')),
                ('footertext', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductSizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('off_price', models.IntegerField(blank=True, null=True)),
                ('picture', models.ImageField(upload_to='products/%Y/%m/%d')),
                ('size', models.ManyToManyField(blank=True, related_name='sizes', to='shop.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
