# Generated by Django 3.2.3 on 2022-02-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='off_price',
            field=models.IntegerField(blank=True, default=75000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productsizes',
            name='off_price',
            field=models.IntegerField(blank=True, default=75000),
            preserve_default=False,
        ),
    ]
