# Generated by Django 3.2.3 on 2022-02-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20220204_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='productsizes',
            name='product',
            field=models.ManyToManyField(blank=True, to='shop.Product'),
        ),
    ]
