# Generated by Django 3.2.3 on 2022-02-04 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20220204_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsizes',
            name='product',
        ),
        migrations.AddField(
            model_name='productsizes',
            name='product',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
            preserve_default=False,
        ),
    ]
