# Generated by Django 3.2.3 on 2022-02-05 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20220204_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsizes',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
    ]
